### ISSUE TITLE
Update OMERO dependencies to new groupID

### ISSUE THREAD

**Issue by imagejan** [imagej/imagej-omero#106]
Since version 5.5.0, the OMERO component artifacts changed their groupId from `omero` to `org.openmicroscopy`. See [this forum topic](https://forum.image.sc/t/release-of-omero-5-5-0/26600/7?u=imagejan).

**Comment by ctrueden** [comment]
Was done with f1846f570906b30e39d2546ccc660c6a69a08cc0. But more work still needed to make things actually work with OMERO 5.5+. See #107 and scijava/pom-scijava#122.
