### ISSUE TITLE
Import Key/Value pairs from OMERO

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-omero#111]
Currently we are not pulling in the Key-Value Pairs metadata when importing images from OMERO:

![image](https://user-images.githubusercontent.com/1123809/178558781-f83ff32d-68bb-4eac-8375-c893cd7c0bbf.png)

I believe this information should be stuffed into the `OMEROFormat.Metadata` global map on import, and exported appropriately.

**Comment by hinerm** [comment]
@joshmoore I was looking at [the documentation](https://docs.openmicroscopy.org/omero/5.6.0/developers/Model/KeyValuePairs.html) for how to access Key-Value pairs. I thought that, after [opening the pixels](https://github.com/imagej/imagej-omero/blob/a51f312a854d8e4e28bd3c9c86db65bddcc4330a/src/main/java/net/imagej/omero/OMEROFormat.java#L453) I could go `Pixels -> Image -> ImagingEnvironment -> Map` and get to the K-V pairs... but when I tried it, I found the attached `ImagingEnvironment` is `null` at this point.

Can you point me at the correct API way to access the K-V pairs for an image?

Thank you!

**Comment by joshmoore** [comment]
Hey @hinerm. Sorry for the slow response. I assume you're looking for the connection to the Key-Value pairs that are on the right-hand panel of the GUI? If so, you're looking for the MappAnnotations with the connection `Pixels -> Image -> AnnotationLinks -> Annotations -> Map`.

**Comment by joshmoore** [comment]
> which seems to load the annotations directly, albeit in a more unwieldly `IObject` format.. and `Image.linkedAnnotationList()` still throws the `UnloadedEntityException`..

Each remote call loads a separate graph. No attempt is made to update existing objects (though there are local methods for doing that if necessary)

> I can just do a test and cast to `omero.model.MapAnnotationI` and get my Key-Value pairs,

The third argument will let you choose _only_ MapAnnotations. See https://downloads.openmicroscopy.org/omero/5.4.6/api/slice2html/omero/api/IMetadata.html#loadAnnotations

> but I'm curious how to make the `Image.linkedAnnotationList()` pathway work?

Then the original loading method would need to traverse the graph down to annotations. How are the images loaded?

**Comment by hinerm** [comment]
@dominikl works perfectly - thanks for the snippet!
