### ISSUE TITLE
Put generated images into an ImageJ project & dataset

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-omero#23]
Right now, Images are not assigned to any Dataset, so web shows them as "orphaned". Let's assign them to a default dataset and project called "ImageJ" if no better dataset destination is known (see also #22).

**Comment by awalter17** [comment]
Additionally we need to figure out how we would like to handle images created from other images. Do we want to try to link them to one another or is it sufficient to just have them in the same Dataset?

**Comment by ctrueden** [comment]
Resolved by #65.
