### ISSUE TITLE
vessel segmentation with Caffe

### ISSUE THREAD

**Issue by wangchuanxd** [imagej/imagej-omero#50]
as the title mentioned, my problem is: could caffe deal with the 3D vessel images? if so, how can I   input the 3D data with Caffe? my 3D data format now is .mat. I appreciate to someone who can solve my puzzle so much !

**Comment by ctrueden** [comment]
This repository is for [ImageJ](http://imagej.net/) integration with [OMERO](http://openmicroscopy.org/info/omero). For questions about [Caffe](http://caffe.berkeleyvision.org/) please use the [caffe-users](https://groups.google.com/forum/#!forum/caffe-users) group.

**Comment by wangchuanxd** [comment]
ok, I am a new comer, I am terribly sorry for what I have done

**Comment by ctrueden** [comment]
@wangchuanxd No worries. Good luck getting your question answered!
