### ISSUE TITLE
Study pom-omero-client

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-omero#64]
OMERO now has a [pom-omero-client](https://github.com/ome/pom-omero-client/blob/dev_5_1/pom.xml) designed for OMERO clients to extend. Of course, we want to extend `pom-scijava` for this component, but we could _import_ `pom-omero-client`, and/or lift helpful bits from it as appropriate.

**Comment by mtbc** [comment]
Out of curiosity have you any thoughts on https://github.com/ome/pom-omero-client/pull/30#issuecomment-334758662?

**Comment by ctrueden** [comment]
@mtbc @sbesson @joshmoore Sorry for the long delay in reply. If there is anything I can do to help with Maven-related issues while I am visiting Dundee, please let me know.

On the ImageJ-OMERO side, I'm satisfied with the pom-scijava management of OME components. But I'm still open to using import scope of pom-omero-client in pom-scijava. Shall we spend a little time tomorrow discussing it, and related pom-scijava things?
