### ISSUE TITLE
Add option to download / upload several images to the OMEROService

### ISSUE THREAD

**Issue by gab1one** [imagej/imagej-omero#67]
## Goal

Transfer large amounts of images/Data to and from an OMERO server. 
## Problem

The current implementation opens a new connection to the OMERO server for each transaction (downloading / uploading  an image). This introduces overhead in the order of seconds.
## Solution sketch
- Add methods like the following to `OMEROService:`

``` java
/**
* Uploads the given images to the omero server
* @return A collection of the imageIDs for the uploaded images
*/
public Collection<Long> uploadImages(..., Collection<ImgPlus<?>> imgs);

/**
* @return A collection of images downloaded from the omero server
*/
public Collection<ImgPlus<?> downloadImages(... ,Collection<Long> imageIds);
```
- The implementation will reuse one reader/writer and one connection to the server to
  increase performance.

I will start to implement this, probably based on @awalter17's code in the tables branch. @ctrueden do you have any remarks to add?

**Comment by ctrueden** [comment]
@gab1one Are you actually actively working on this? If not, please unassign yourself.

**Comment by gab1one** [comment]
@ctrueden I think this issue is no longer relevant, with the new architecture, we do not recreate sessions all the time, so we do not need a special case for multifile transfer.
