### ISSUE TITLE
Rogue UUIDs in generated ImageJ script names

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej-omero#80]
There is a sequence of characters in UUID format before each script (ex: `84f05d92-794b-11e8-bcf9-6c4008b90c48`) when you run `gen-scripts`. These go away if you run it a second time. Maybe a sessionID?

Noticed by @awalter17.

**Comment by ctrueden** [comment]
To be clear: the sequence of characters is _not_ in the generated script wrapper filenames, and not in the generated script wrapper _contents_. It only appears when you run `omero script list` in the output of that command. And similarly, in OMERO.web's listing. This seems like a bug in OMERO to me. What do you think, @joshmoore?

**Comment by ctrueden** [comment]
If you run `omero script list` a second time, even immediately, the UUIDs are gone.

**Comment by joshmoore** [comment]
@ctrueden : this is a race-condition as the server pre-processes the new scripts stemming from the migration to periodic checks in https://github.com/openmicroscopy/openmicroscopy/pull/3790

Calling `script list` after a re-deployment of the .jy files and/or restarting the server will prevent it from happening. If that's sufficient, then likely adding a workaround of 2 calls to `script list` as you mention is the best option.

**Comment by mtbc** [comment]
I'll see if I can figure a fix for this in OMERO. You're right @ctrueden: it shouldn't be happening in the first place.

**Comment by ctrueden** [comment]
Thanks @mtbc. I was not able to work around the issue on the ImageJ-OMERO side; the `gen-scripts` script would need to invoke `omero script` a couple of times, which would require the user to authenticate (as an admin?).

**Comment by joshmoore** [comment]
Sorry for leaving this dangling. @mtbc fixed this for OMERO.server 5.4.7.
