### ISSUE TITLE
Password and recorder

### ISSUE THREAD

**Issue by jburel** [imagej/imagej-omero#93]
* Start the recorder
* Run the command ``File > Import >OMERO``
* The password is displayed. This should be hidden

**Comment by joshmoore** [comment]
@jburel, you mean a la:

```
IJ.run("OMERO...", "server=host port=4064 user=public password=public imageid=234234 downloadtables=false downloadrois=false")
```

?

If so, then I'm not sure I agree. If the user is looking for a macro that actually works, then this will be necessary. It is local so the risk is minimal (until they share!).

The only other option I can think of is:

```
String pw = ask_for_password();
IJ.run("OMERO...", String.format("server=host port=4064 user=public password=%s imageid=234234 downloadtables=false downloadrois=false", pw));
```

**Comment by jburel** [comment]
I was more thinking of someone demoing and using for example LDAP credentials
w/o realising that the password was not hidden
If it is to build an example yes it is not different than the current scripts we have
