### ISSUE TITLE
Load rois and ROI manager

### ISSUE THREAD

**Issue by jburel** [imagej/imagej-omero#98]
The rois loaded are added to the  display
They should probably be also added to ROIManager.

**Comment by ctrueden** [comment]
Adding them to the ROI Manager by default could potentially pollute or stomp a user's existing ROIs there. Keeping them only as an overlay initially is safer. The user can run the "To ROI Manager" command to export/copy an IJ1 overlay to the ROI Manager as desired.

**Comment by ctrueden** [comment]
One compromise could be to add an "Add ROIs to manager" checkbox to the `OpenFromOMERO` command, unchecked by default, but which does this automatically. ImageJ1 has that checkbox in other commands that work with ROIs (e.g. Analyze Particles), and users are familiar with it.

**Comment by jburel** [comment]
the suggested option will work
